// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ_EG8q9VpoOsCaXH7A7ypFS5lizS_feg',
    appId: '1:868403001816:web:ac85178860032e1c835aad',
    messagingSenderId: '868403001816',
    projectId: 'image-upload-de7d9',
    authDomain: 'image-upload-de7d9.firebaseapp.com',
    storageBucket: 'image-upload-de7d9.firebasestorage.app',
    measurementId: 'G-5JPVEBXFMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQcfYs7vlgoSvxhuLvHqwDlmiIc907f2o',
    appId: '1:868403001816:android:459d532af402ac77835aad',
    messagingSenderId: '868403001816',
    projectId: 'image-upload-de7d9',
    storageBucket: 'image-upload-de7d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-yU-X_W9fCXVUrpUP4kIRHi8H96xfFzU',
    appId: '1:868403001816:ios:91a82371d13e0341835aad',
    messagingSenderId: '868403001816',
    projectId: 'image-upload-de7d9',
    storageBucket: 'image-upload-de7d9.firebasestorage.app',
    iosBundleId: 'com.example.imageUpload',
  );

}